# Generated by Django 5.1.3 on 2024-11-05 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('survey_type', models.CharField(choices=[('account_cancel', 'Account_Cancel')], max_length=50)),
            ],
        ),
    ]
