# Generated by Django 5.1.3 on 2024-11-05 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Announcement_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Company_Announcement_Subject', models.CharField(max_length=255)),
                ('Company_Announcement_Content', models.TextField()),
            ],
        ),
    ]
