# Generated by Django 5.1.3 on 2024-11-05 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inquiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Inquiry_type', models.CharField(max_length=50)),
                ('Inquiry_subject', models.CharField(max_length=500)),
                ('Inquiry_main_content', models.TextField()),
                ('Inquiry_reply', models.TextField(blank=True, null=True)),
                ('Inquiry_reply_date', models.DateTimeField(blank=True, null=True)),
                ('is_replied', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
